### ISSUE TITLE
Goal: audit smart contacts

### ISSUE THREAD

**Issue by markholdex** [truflation/truflation-contracts#29]
_Originally posted by @zolotokrylin in https://github.com/truflation/tfi-claim-page/issues/7#issuecomment-2049202054_

# Problems
- [x] truflation/tfi-claim-page#116
- [x] Problem: auditor team not invited to contracts repositories
- [x] truflation/truflation-contracts#38
- [x] truflation/truf-claim-page#40 

# Audit Findings
### High
- [x] truflation/truf-claim-page#214
- [x] truflation/truf-claim-page#215
- [x] truflation/truf-claim-page#216
### Medium
- [x] truflation/truf-claim-page#217
- [x] truflation/truf-claim-page#218
- [x] truflation/truf-claim-page#219
- [x] truflation/truf-claim-page#220
- [x] truflation/truf-claim-page#221
- [x] truflation/truf-claim-page#222
- [x] truflation/truf-claim-page#223
### Low
- [x] truflation/truf-claim-page#224
- [x] truflation/truf-claim-page#225
- [x] truflation/truf-claim-page#226
- [x] truflation/truf-claim-page#227
- [x] truflation/truf-claim-page#228
- [x] truflation/truf-claim-page#229
- [x] truflation/truf-claim-page#230
- [x] truflation/truf-claim-page#231
- [x] truflation/truf-claim-page#232
- [x] truflation/truf-claim-page#233

# Blocks
- https://github.com/truflation/truf-claim-page/issues/7
# Blocked by 
- [x] truflation/truflation-contracts#28

**Comment by zolotokrylin** [comment]
The expected date of the audit reported is May 11th.

**Comment by zolotokrylin** [comment]
Updated date: May 8th.

**Comment by stronghold-audit** [comment]
Here's the interim audit report @zolotokrylin

[TruFlation Interim Audit Report.md](https://github.com/truflation/truflation-contracts/files/15252706/TruFlation.Interim.Audit.Report.md)
[M4M6proofs.zip](https://github.com/truflation/truflation-contracts/files/15252709/M4M6proofs.zip)

**Comment by zolotokrylin** [comment]
@Dev-Doggo how much more time do you need before we can revert back to our auditor?

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo how much more time do you need before we can revert back to our auditor? We need to release ASAP.

@zolotokrylin I've created PRs or addressed all of the issues they've raised, the rest is up to you guys to review and merge 😅

**Comment by zolotokrylin** [comment]
log: I have pinged @stronghold-audit team in Telegram and relevant Github issues. We are waiting for them to revert.

**Comment by Dev-Doggo** [comment]
Seems like we've finalized all of the required changes for the issues, can we get stronghold back to working on this?

cc @zolotokrylin @markholdex

**Comment by stronghold-audit** [comment]
[Truflation Contracts Security Audit Report.pdf](https://github.com/truflation/truflation-contracts/files/15334465/Truflation.Contracts.Security.Audit.Report.pdf)

Resume:

I have canceled and removed from final report:
H-2 Any unused TRUF tokens will be stuck on the contract when liquidity is added (HIGH)

I have removed from final report:
L-1 Missing sanity checks (LOW)
L-2 Magic constants (LOW) 
L-6 Missing upgrade events (LOW)

I have moved and updated the description:
H-1 -> M-8 The owner can't cancel a subscription (HIGH to MED)

**Comment by markholdex** [comment]
@Dev-Doggo everything has been fixed. Congratz. 🚀  We can close this Goal.
<img width="782" alt="image" src="https://github.com/truflation/truflation-contracts/assets/46079535/33e4d7e8-7565-4dff-88b3-f8bab0eb0353">
